# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Erwin Chow' Blog
email: erwin00776@163.com
description: bala bala bala...
baseurl: "" # the subpath of your site, e.g. /blog
url: "erwin00776.github.io" # the base hostname & protocol for your site
twitter_username: (NULL)
github_username:  (NULL)

# Build settings
markdown: kramdown
